[package]

# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "RL Training Repo for DeepRobotics"
author = "Bo Peng"
maintainer = "Bo Peng"
description="RL Training Repo for DeepRobotic, Based on IsaacLab."
repository = "https://github.com/DeepRoboticsLab/rl_training.git"
keywords = ["extension", "rl_training", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "rl_training"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
